---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 18674.
--- DateTime: 2026/9/14 10:57
---
local voucherId=ARGV[1]
local key='seckill:stock:' .. voucherId
local userId=ARGV[2]
local keyy='seckill:order:' .. voucherId
local id=ARGV[3]
--- 检查库存
if(tonumber(redis.call('get',key))<=0) then
    return 1
end
--- 检测一人一单
if(redis.call('sismember',keyy,userId)==1) then
    return 2
end

redis.call('sadd',keyy,userId)
redis.call('incrby',key,-1)

redis.call('xadd','stream.setKillOrder','*','id',id,'voucherId',voucherId,'userId',userId)
return 0