---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 18674.
--- DateTime: 2026/9/12 10:50
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0